package frames;



import javax.swing.JFrame;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Rohini
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public Home() {
        initComponents();
//        final JFrame frame = new JFrame();
//         frame = new JFrame(gc);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
//        this.setExtendedState(this.getExtendedState() | this.MAXIMIZED_BOTH);
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        newStd = new javax.swing.JButton();
        newBk = new javax.swing.JButton();
        issueBk = new javax.swing.JButton();
        returnBk = new javax.swing.JButton();
        logOut = new javax.swing.JButton();
        newStat = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Library_Book_532388_1366x768.jpg"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel3.setMaximumSize(new java.awt.Dimension(1400, 1200));
        jLabel3.setMinimumSize(new java.awt.Dimension(1400, 1200));
        jLabel3.setPreferredSize(new java.awt.Dimension(1400, 1200));
        jLabel3.setVerifyInputWhenFocusTarget(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(325, 125));
        setResizable(false);
        setSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        newStd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/member-add-on-300x300.png"))); // NOI18N
        newStd.setText("New Student");
        newStd.setMaximumSize(new java.awt.Dimension(149, 59));
        newStd.setPreferredSize(new java.awt.Dimension(159, 59));
        newStd.setRolloverEnabled(false);
        newStd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newStdActionPerformed(evt);
            }
        });
        getContentPane().add(newStd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 160, -1));

        newBk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New book.png"))); // NOI18N
        newBk.setText("New Book");
        newBk.setPreferredSize(new java.awt.Dimension(159, 59));
        newBk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBkActionPerformed(evt);
            }
        });
        getContentPane().add(newBk, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        issueBk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library/issue.png"))); // NOI18N
        issueBk.setText("Issue Book");
        issueBk.setPreferredSize(new java.awt.Dimension(159, 59));
        issueBk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueBkActionPerformed(evt);
            }
        });
        getContentPane().add(issueBk, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, -1, -1));

        returnBk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library/return-book-1-560407.png"))); // NOI18N
        returnBk.setText("Return Book");
        returnBk.setPreferredSize(new java.awt.Dimension(159, 59));
        returnBk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBkActionPerformed(evt);
            }
        });
        getContentPane().add(returnBk, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 10, -1, -1));

        logOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library/exit.png"))); // NOI18N
        logOut.setText("LogOut");
        logOut.setPreferredSize(new java.awt.Dimension(159, 59));
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });
        getContentPane().add(logOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 10, 130, -1));

        newStat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library/Statics.png"))); // NOI18N
        newStat.setText("Statistics");
        newStat.setPreferredSize(new java.awt.Dimension(159, 59));
        newStat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newStatActionPerformed(evt);
            }
        });
        getContentPane().add(newStat, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, -1, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Library_Book_532388_1366x768.jpg"))); // NOI18N
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1420, 820));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newStdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newStdActionPerformed
        new newStudent().setVisible(true);
        
    }//GEN-LAST:event_newStdActionPerformed

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new LoginPage().setVisible(true);
    }//GEN-LAST:event_logOutActionPerformed

    private void newBkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBkActionPerformed
        //new book 
        new newBook().setVisible(true);
        
    }//GEN-LAST:event_newBkActionPerformed

    private void issueBkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueBkActionPerformed
       //issue book
       new issueBook().setVisible(true);
    }//GEN-LAST:event_issueBkActionPerformed

    private void returnBkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBkActionPerformed
        
        new returnBook().setVisible(true);
    }//GEN-LAST:event_returnBkActionPerformed

    private void newStatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newStatActionPerformed
        // TODO add your handling code here:
        new statistics().setVisible(true);
    }//GEN-LAST:event_newStatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton issueBk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton logOut;
    private javax.swing.JButton newBk;
    private javax.swing.JButton newStat;
    private javax.swing.JButton newStd;
    private javax.swing.JButton returnBk;
    // End of variables declaration//GEN-END:variables
}
